version: "3.8"

services:
  gateway-server:
    build: ./gatewayServer
    ports:
      - "4000:4000"
    networks:
      - my_network
    volumes:
      - ./gatewayServer:/usr/src/app

  catalog-server:
    build: ./catalogServer
    ports:
      - "4001:4001"
    networks:
      - my_network
    volumes:
      - ./catalogServer:/usr/src/app

  order-server:
    build: ./orderServer
    ports:
      - "4002:4002"
    networks:
      - my_network
    volumes:
      - ./orderServer:/usr/src/app

networks:
  my_network:
    driver: bridge
